/**
 * One entry on the longitudinal timeline.
 *
 * Machine and human authorship are distinguished four ways, because this is the
 * distinction the brief's whole trust argument rests on and one signal is not
 * enough: a dashed rather than solid rail, a different rail colour, a monospace
 * rather than humanist body face, and an explicit "AI scribed" label with the
 * model and redaction count beside it. Take away colour and it still reads;
 * take away the label and it still reads.
 *
 * The AI-scribed card also carries what a clinician needs to decide how much to
 * trust it: the confidence figure, how many identifiers were stripped before
 * the text was summarised, and a link back to the originating session. An
 * assertion with no way to check it is the thing this product exists to
 * replace.
 */

import { useRef, useState } from 'react'
import { Api } from '../lib/api'
import { ROLE_ACCENT, entryLabel, relativeAge, roleLabel, shortDateTime } from '../lib/format'
import Comments from './Comments'
import VersionHistory from './VersionHistory'
import { TranscriptToggle } from './TranscriptPanel'
import {
  Button,
  Chip,
  ConfidenceChip,
  RiskChip,
  SpanText,
  readSelectionRange,
} from './Primitives'

export default function EntryCard({
  entry,
  emphasis,
  users,
  canComment,
  canHighlight,
  canRestore,
  onChanged,
  registerRef,
}) {
  const [open, setOpen] = useState(null) // 'comments' | 'history' | 'edit' | 'correct'
  const [selection, setSelection] = useState(null)
  const [draft, setDraft] = useState(entry.content)
  const [correction, setCorrection] = useState('')
  const [error, setError] = useState(null)
  const [notice, setNotice] = useState(null)
  const [busy, setBusy] = useState(false)
  const contentRef = useRef(null)

  const isAi = entry.is_ai_scribed
  const accent = ROLE_ACCENT[entry.author_role] || 'border-l-slate-300'
  // A cold entry shows a compressed summary. The full text is one audited
  // click away — the point of saying so on the card is that a clinician should
  // never be reading a shortened note while believing it is the whole one.
  const isArchived = entry.decay_state === 'cold'

  function captureSelection() {
    if (!canHighlight) return
    setSelection(readSelectionRange(contentRef.current))
  }

  async function highlightSelection() {
    if (!selection) return
    setBusy(true)
    try {
      await Api.manualHighlight(entry.id, {
        span_start: selection.start,
        span_end: selection.end,
      })
      setSelection(null)
      setNotice('Highlighted — now pinned to the Glance View.')
      onChanged?.()
    } catch (err) {
      setError(err.message)
    } finally {
      setBusy(false)
    }
  }

  async function saveEdit() {
    setBusy(true)
    setError(null)
    try {
      await Api.updateEntry(entry.id, {
        content: draft,
        title: entry.title,
        expected_version: entry.version_number,
        change_summary: 'edited in consult',
      })
      setOpen(null)
      onChanged?.()
    } catch (err) {
      // A 409 carries the current state, so the message can say what actually
      // happened rather than "please try again".
      if (err.status === 409 && err.detail?.current_version) {
        setError(
          `${err.detail.message} You were editing v${err.detail.expected_version}; ` +
            `the note is now at v${err.detail.current_version}.`
        )
      } else {
        setError(err.message)
      }
    } finally {
      setBusy(false)
    }
  }

  async function restoreArchived() {
    setBusy(true)
    setError(null)
    try {
      await Api.restoreEntry(entry.id)
      setNotice('Full note restored from the archive.')
      onChanged?.()
    } catch (err) {
      setError(err.message)
    } finally {
      setBusy(false)
    }
  }

  async function saveCorrection() {
    setBusy(true)
    setError(null)
    try {
      await Api.supersede(entry.id, {
        content: correction,
        title: 'Clinician correction',
        risk_level: entry.risk_level === 'none' ? 'low' : entry.risk_level,
        reason: 'clinician disagreed with this entry',
      })
      setCorrection('')
      setOpen(null)
      onChanged?.()
    } catch (err) {
      setError(err.message)
    } finally {
      setBusy(false)
    }
  }

  return (
    <li
      ref={registerRef}
      id={`entry-${entry.id}`}
      className={`scroll-mt-24 border-l-4 bg-white p-3 shadow-sm ring-1 ring-slate-200 ${accent}`}
    >
      <div className="flex flex-wrap items-center gap-1.5">
        {isAi ? (
          <Chip tone="ai" title="Generated by the scribe pipeline, not written by a person">
            ◇ AI scribed
          </Chip>
        ) : (
          <Chip tone="human">• {roleLabel(entry.author_role)}</Chip>
        )}
        <span className="text-xs font-medium text-slate-800">{entryLabel(entry.type)}</span>
        <span className="text-[11px] text-slate-500">
          {entry.author_name || entry.author_id}
        </span>
        <RiskChip level={entry.risk_level} />
        {isAi && <ConfidenceChip confidence={entry.ai_confidence} />}
        {entry.conflict_flagged && (
          <Chip tone="alert" title="A clinician has recorded a correction to this entry">
            Disputed — see correction
          </Chip>
        )}
        {entry.supersedes_entry_id && <Chip tone="info">Corrects an earlier entry</Chip>}
        {isArchived && (
          <Chip
            tone="neutral"
            title="Older entry. The full text is archived and can be restored."
          >
            ▤ Archived — summary shown
          </Chip>
        )}
        <span
          className="ml-auto font-mono text-[10px] text-slate-400"
          title={shortDateTime(entry.timestamp)}
        >
          {shortDateTime(entry.timestamp)} · {relativeAge(entry.timestamp)}
        </span>
      </div>

      {entry.title && (
        <h4 className="mt-1.5 text-sm font-semibold text-slate-900">{entry.title}</h4>
      )}

      <div ref={contentRef} onMouseUp={captureSelection} className="mt-1">
        <SpanText content={entry.content} emphasis={emphasis} mono={isAi} />
      </div>

      {isArchived && (
        <div className="mt-1.5 flex flex-wrap items-center gap-2 rounded bg-slate-50 px-2 py-1 ring-1 ring-slate-200">
          <span className="text-[11px] text-slate-600">
            This is a shortened copy. Every sentence shown was written by the author —
            nothing has been rephrased.
          </span>
          {canRestore && (
            <Button variant="quiet" disabled={busy} onClick={restoreArchived}>
              Restore full note
            </Button>
          )}
        </div>
      )}

      {selection && (
        <div className="mt-1 flex items-center gap-2 rounded bg-amber-50 px-2 py-1 ring-1 ring-amber-200">
          <span className="text-[11px] text-amber-900">
            {selection.end - selection.start} characters selected
          </span>
          <Button variant="primary" disabled={busy} onClick={highlightSelection}>
            Highlight this
          </Button>
          <Button variant="quiet" onClick={() => setSelection(null)}>
            Cancel
          </Button>
        </div>
      )}
      {notice && <p className="mt-1 text-[11px] text-emerald-700">{notice}</p>}
      {error && <p className="mt-1 text-xs text-rose-700">{error}</p>}

      {/* Provenance line. Always present, on every entry type — a manual note is
          its own provenance, an AI note points at the session behind it. */}
      <div className="mt-1.5 flex flex-wrap items-center gap-x-3 gap-y-1 font-mono text-[10px] text-slate-400">
        <span title="Provenance pointer">{entry.provenance_pointer}</span>
        <span>v{entry.version_number}</span>
        {isAi && entry.ai_model_used && <span>model {entry.ai_model_used}</span>}
        {isAi && entry.ai_redaction_count !== null && (
          <span title="Identifiers removed before this transcript reached a model">
            {entry.ai_redaction_count} identifiers redacted
          </span>
        )}
      </div>

      <div className="mt-2 flex flex-wrap gap-1">
        {canComment && (
          <Button onClick={() => setOpen(open === 'comments' ? null : 'comments')}>
            Discussion
            {entry.comment_count > 0 && (
              <span className="ml-1 font-mono text-[10px] text-slate-500">
                {entry.open_comment_count > 0
                  ? `${entry.open_comment_count} open`
                  : entry.comment_count}
              </span>
            )}
          </Button>
        )}
        <Button onClick={() => setOpen(open === 'history' ? null : 'history')}>
          History <span className="ml-1 font-mono text-[10px] text-slate-500">v{entry.version_number}</span>
        </Button>
        {/* Only renders for AI-scribed entries that have a stored session —
            a note scribed from a fixture has no captured audio behind it. */}
        {canComment && <TranscriptToggle entry={entry} />}
        {entry.editable_by_me && (
          <Button
            onClick={() => {
              setDraft(entry.content)
              setOpen(open === 'edit' ? null : 'edit')
            }}
          >
            Edit
          </Button>
        )}
        {canHighlight && (isAi || entry.author_role === 'patient') && (
          <Button
            variant="reject"
            onClick={() => setOpen(open === 'correct' ? null : 'correct')}
            title="Record a clinician correction. The original stays on the record, flagged."
          >
            Correct this
          </Button>
        )}
        {canHighlight && (
          <span className="self-center text-[11px] text-slate-400">
            Select any text above to highlight it
          </span>
        )}
      </div>

      {open === 'edit' && (
        <div className="mt-2 rounded border border-slate-300 bg-slate-50 p-2">
          <textarea
            className="w-full rounded border border-slate-300 p-2 text-sm"
            rows={5}
            value={draft}
            onChange={(event) => setDraft(event.target.value)}
          />
          <p className="mt-1 text-[11px] text-slate-500">
            Saving creates version {entry.version_number + 1}. The current text is kept
            in history, and can be restored.
          </p>
          <div className="mt-1 flex gap-1">
            <Button variant="primary" disabled={busy} onClick={saveEdit}>
              {busy ? 'Saving…' : 'Save changes'}
            </Button>
            <Button variant="quiet" onClick={() => setOpen(null)}>
              Cancel
            </Button>
          </div>
        </div>
      )}

      {open === 'correct' && (
        <div className="mt-2 rounded border border-slate-300 bg-amber-50/60 p-2">
          <p className="text-[11px] text-slate-700">
            Your correction takes effect immediately and this entry stays on the record,
            flagged as disputed. Nothing is deleted.
          </p>
          <textarea
            className="mt-1 w-full rounded border border-slate-300 p-2 text-sm"
            rows={3}
            value={correction}
            onChange={(event) => setCorrection(event.target.value)}
            placeholder="What the record should say instead."
          />
          <div className="mt-1 flex gap-1">
            <Button variant="primary" disabled={busy || !correction.trim()} onClick={saveCorrection}>
              Record correction
            </Button>
            <Button variant="quiet" onClick={() => setOpen(null)}>
              Cancel
            </Button>
          </div>
        </div>
      )}

      {open === 'comments' && canComment && (
        <Comments entry={entry} users={users} onChanged={onChanged} />
      )}
      {open === 'history' && (
        <VersionHistory
          entry={entry}
          canRevert={entry.editable_by_me}
          onChanged={onChanged}
        />
      )}
    </li>
  )
}
